/* ============================================================================
 * forecast.js — A PROBABILISTIC FORECAST OF NEXT YEAR'S INCOME
 * ----------------------------------------------------------------------------
 * This is the machine learning core of the project, and it exists because two
 * of our headline features are impossible without it:
 *
 *   advancetax.js  needs F-inverse(p) — the p-th percentile of your income —
 *                  to place each instalment. A point estimate is useless to it,
 *                  because the cost of being wrong is asymmetric.
 *   stopping.js    needs E[V(next year)] — an expectation over where your
 *                  income might land — to value an irreversible regime switch.
 *
 * Both need a DISTRIBUTION, not a number. So that is what this file returns.
 *
 * ----------------------------------------------------------------------------
 * TWO TIERS, AND WHY
 * ----------------------------------------------------------------------------
 * Tier 1  ANALYTIC PRIOR. A lognormal random walk with drift, with parameters
 *         set per employment type. Needs no training data and no download, so
 *         the app works the moment it is opened. This is the baseline the
 *         trained model has to beat.
 *
 * Tier 2  TRAINED QUANTILE MODEL, loaded from models/forecaster.json when it
 *         is present. Quantile regression fitted at a grid of quantiles, which
 *         lets it learn things the lognormal cannot: right skew from job
 *         changes, fatter tails for the self-employed, the fact that variable
 *         pay widens the distribution without moving its centre.
 *
 * The tiering is deliberate. It degrades gracefully, and it gives us a
 * BASELINE TO MEASURE AGAINST — ml/train_forecaster.py reports the trained
 * model's pinball loss against this prior's. "Our model is better" is only a
 * claim worth making when there is something it is better than.
 *
 * ----------------------------------------------------------------------------
 * HONESTY NOTE — PLEASE READ BEFORE PRESENTING THIS
 * ----------------------------------------------------------------------------
 * There is no public dataset of individual Indian taxpayers' income histories,
 * for obvious privacy reasons. The trained model is therefore fitted on a
 * SYNTHETIC population generated by ml/generate_population.py, calibrated
 * against published aggregate statistics. That is a legitimate way to build
 * and test the machinery, and it is how the method would be validated before
 * being fitted on real data — but it must never be described as a model
 * trained on real taxpayers. Say "calibrated synthetic population". The
 * `provenance` field on every prediction carries this through to the UI.
 * ========================================================================== */

/* ---------- helpers ------------------------------------------------------ */

const fNum = (v) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
};

/**
 * Inverse standard normal CDF — Acklam's rational approximation, accurate to
 * about 1.15e-9 across the whole range. We need this to turn a probability
 * into a z-score for the lognormal prior's quantile function.
 */
function probit(p) {
  if (p <= 0) return -Infinity;
  if (p >= 1) return Infinity;

  const a = [-3.969683028665376e+01, 2.209460984245205e+02, -2.759285104469687e+02,
             1.383577518672690e+02, -3.066479806614716e+01, 2.506628277459239e+00];
  const b = [-5.447609879822406e+01, 1.615858368580409e+02, -1.556989798598866e+02,
             6.680131188771972e+01, -1.328068155288572e+01];
  const c = [-7.784894002430293e-03, -3.223964580411365e-01, -2.400758277161838e+00,
             -2.549732539343734e+00, 4.374664141464968e+00, 2.938163982698783e+00];
  const d = [7.784695709041462e-03, 3.224671290700398e-01, 2.445134137142996e+00,
             3.754408661907416e+00];

  const pLow = 0.02425;
  const pHigh = 1 - pLow;
  let q, r;

  if (p < pLow) {
    q = Math.sqrt(-2 * Math.log(p));
    return (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
           ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1);
  }
  if (p > pHigh) {
    q = Math.sqrt(-2 * Math.log(1 - p));
    return -(((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
            ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1);
  }
  q = p - 0.5;
  r = q * q;
  return (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q /
         (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1);
}

/**
 * A seeded generator, so that a demo run is reproducible. Monte Carlo results
 * that change every refresh are impossible to discuss in a viva.
 */
function makeRng(seed) {
  let s = (seed === undefined ? 12345 : seed) >>> 0;
  return function () {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5;  s >>>= 0;
    return s / 4294967296;
  };
}

/* ============================================================================
 * TIER 1 — THE ANALYTIC PRIOR
 * ==========================================================================*/

/**
 * Log-income is modelled as a random walk with drift:
 *
 *     log Y(t+1) = log Y(t) + mu + sigma * Z,     Z ~ N(0,1)
 *
 * so Y(t+1) is lognormal and its quantile function is available in closed
 * form. `mu` is expected growth; `sigma` is how uncertain that growth is.
 *
 * These numbers are ASSUMPTIONS, not measurements, and they are written here
 * rather than buried so that they can be argued with:
 *
 *   salaried      steady increments, occasionally a job change. Moderate
 *                 drift, low spread.
 *   professional  fee income; a good year and a bad year differ a lot.
 *   business      the widest spread of the three — a business can double or
 *                 halve in a way a salary cannot.
 *
 * Variable pay (bonus, RSUs, incentives) widens the spread without moving the
 * centre, which is why it enters sigma and not mu.
 */
const PRIOR_PARAMS = {
  salaried:     { mu: 0.080, sigma: 0.14 },
  professional: { mu: 0.070, sigma: 0.28 },
  business:     { mu: 0.065, sigma: 0.35 },
};

/**
 * Growth slows down over a career. A 25-year-old's income compounds faster
 * than a 55-year-old's, so we taper the drift with age.
 */
function ageTaper(age) {
  if (!age || age < 25) return 1.15;
  if (age < 35) return 1.10;
  if (age < 45) return 1.00;
  if (age < 55) return 0.80;
  return 0.55;
}

function priorParams(features) {
  const type = PRIOR_PARAMS[features.employmentType] ? features.employmentType : 'salaried';
  const base = PRIOR_PARAMS[type];

  const mu = base.mu * ageTaper(features.age);

  // Variable pay is the single biggest driver of forecast uncertainty for a
  // salaried taxpayer, and it is the reason a senior engineer with 40% of pay
  // in RSUs is harder to forecast than a clerk on a flat salary.
  const variableShare = Math.max(0, Math.min(1, fNum(features.variableShare)));
  const sigma = base.sigma * (1 + 0.9 * variableShare);

  return { mu, sigma, type };
}

/* ============================================================================
 * TIER 2 — INFERENCE FOR THE TRAINED QUANTILE MODEL
 * ==========================================================================*/

/**
 * Walk one regression tree exported from scikit-learn. The export keeps the
 * arrays sklearn already uses internally, so this is a direct transcription
 * rather than a reimplementation.
 */
function walkTree(tree, x) {
  let node = 0;
  while (tree.children_left[node] !== -1) {
    node = x[tree.feature[node]] <= tree.threshold[node]
      ? tree.children_left[node]
      : tree.children_right[node];
  }
  return tree.value[node];
}

/** Score one quantile's model — either a linear fit or a boosted ensemble. */
function scoreQuantile(qm, x) {
  if (qm.kind === 'linear') {
    let y = qm.intercept;
    for (let i = 0; i < qm.coef.length; i++) y += qm.coef[i] * x[i];
    return y;
  }
  // Gradient boosted: initial guess plus a shrunken sum of tree corrections.
  let y = qm.init;
  for (const t of qm.trees) y += qm.learningRate * walkTree(t, x);
  return y;
}

/**
 * Independently fitted quantile regressors are not guaranteed to come out in
 * order — the fitted 60th percentile can land below the fitted 50th. This is
 * the well-known QUANTILE CROSSING problem, and left alone it produces an
 * invalid distribution and nonsensical advice.
 *
 * We repair it the standard way, by sorting. Because a set of quantile
 * estimates and its sorted rearrangement have the same pinball loss in
 * expectation, sorting can only help: it never makes the fit worse and it
 * guarantees a monotone, usable quantile function.
 */
function repairCrossing(values) {
  return values.slice().sort((a, b) => a - b);
}

/* ============================================================================
 * THE PUBLIC INTERFACE
 * ==========================================================================*/

let TRAINED_MODEL = null;

/**
 * Install a trained model (the parsed contents of models/forecaster.json).
 * Called by app.js on start-up if the file is present; if it is absent
 * everything below silently falls back to the prior.
 */
function loadModel(json) {
  if (!json || !json.quantiles || !json.models) return false;
  TRAINED_MODEL = json;
  return true;
}

function hasTrainedModel() {
  return TRAINED_MODEL !== null;
}

/**
 * Assemble the feature vector in the exact order the trained model expects.
 * The order lives in the model file itself so that Python and JavaScript can
 * never silently disagree about which column is which — the single most
 * common way an exported model goes quietly wrong.
 */
function buildFeatureVector(featureNames, features) {
  return featureNames.map((name) => {
    switch (name) {
      case 'logIncome':      return Math.log(Math.max(1, fNum(features.currentIncome)));
      case 'age':            return fNum(features.age);
      case 'expYears':       return fNum(features.expYears);
      case 'variableShare':  return fNum(features.variableShare);
      case 'recentGrowth':   return fNum(features.recentGrowth);
      case 'yearsSinceSwitch': return fNum(features.yearsSinceSwitch);
      case 'isSalaried':     return features.employmentType === 'salaried' ? 1 : 0;
      case 'isProfessional': return features.employmentType === 'professional' ? 1 : 0;
      case 'isBusiness':     return features.employmentType === 'business' ? 1 : 0;
      case 'isMetro':        return features.city === 'metro' ? 1 : 0;
      default:               return 0;
    }
  });
}

/**
 * THE MAIN ENTRY POINT.
 *
 * Returns a distribution object exposing `quantile(p)`, `sample(n)` and a few
 * summary statistics. Everything downstream — the advance tax optimiser, the
 * regime-switch dynamic program — consumes this interface and neither knows
 * nor cares which tier produced it.
 */
function predict(features, opts) {
  const current = Math.max(0, fNum(features.currentIncome));
  const forcePrior = !!(opts && opts.forcePrior);

  /* ---- Tier 2: the trained model, when we have one --------------------- */
  if (TRAINED_MODEL && !forcePrior) {
    const x = buildFeatureVector(TRAINED_MODEL.features, features);
    const grid = TRAINED_MODEL.quantiles;

    // Models predict log growth; convert back to rupees.
    const raw = TRAINED_MODEL.models.map((qm) => scoreQuantile(qm, x));
    const fixed = repairCrossing(raw);
    const levels = fixed.map((logGrowth) => current * Math.exp(logGrowth));

    return makeDistribution({
      kind: 'trained',
      grid,
      levels,
      current,
      provenance: 'Quantile regression trained on a calibrated synthetic population ' +
                  '(ml/generate_population.py). Not fitted on real taxpayer data.',
      metrics: TRAINED_MODEL.metrics || null,
    });
  }

  /* ---- Tier 1: the analytic prior --------------------------------------- */
  const { mu, sigma, type } = priorParams(features);
  return makeDistribution({
    kind: 'prior',
    current,
    mu,
    sigma,
    provenance: 'Lognormal random walk with drift (mu=' + mu.toFixed(3) +
                ', sigma=' + sigma.toFixed(3) + ') for an ' + type + ' taxpayer. ' +
                'Analytic baseline — no training data used.',
  });
}

/**
 * Wraps whichever tier produced the numbers in one common interface.
 */
function makeDistribution(spec) {
  const current = spec.current;

  /** F-inverse(p). This is the function the newsvendor optimiser calls. */
  function quantile(p) {
    const pp = Math.max(1e-6, Math.min(1 - 1e-6, p));

    if (spec.kind === 'prior') {
      return current * Math.exp(spec.mu + spec.sigma * probit(pp));
    }

    // Trained: linear interpolation between the fitted quantile levels, with
    // a lognormal tail beyond the outermost fitted quantiles so that extreme
    // probabilities still return something sensible rather than clipping.
    const grid = spec.grid;
    const levels = spec.levels;

    if (pp <= grid[0]) return levels[0] * Math.exp(0.35 * (probit(pp) - probit(grid[0])));
    const last = grid.length - 1;
    if (pp >= grid[last]) return levels[last] * Math.exp(0.35 * (probit(pp) - probit(grid[last])));

    for (let i = 0; i < last; i++) {
      if (pp >= grid[i] && pp <= grid[i + 1]) {
        const w = (pp - grid[i]) / (grid[i + 1] - grid[i]);
        return levels[i] + w * (levels[i + 1] - levels[i]);
      }
    }
    return levels[last];
  }

  /** Inverse-transform sampling — works for both tiers via `quantile`. */
  function sample(n, seed) {
    const rng = makeRng(seed);
    const out = new Array(n);
    for (let i = 0; i < n; i++) out[i] = quantile(rng());
    return out;
  }

  const median = quantile(0.5);
  const p10 = quantile(0.10);
  const p90 = quantile(0.90);

  // Mean of a lognormal is exp(mu + sigma^2/2); for the trained model we take
  // the numerical mean over a fine grid rather than assume a shape.
  let mean;
  if (spec.kind === 'prior') {
    mean = current * Math.exp(spec.mu + (spec.sigma * spec.sigma) / 2);
  } else {
    let acc = 0;
    const N = 199;
    for (let i = 1; i <= N; i++) acc += quantile(i / (N + 1));
    mean = acc / N;
  }

  return {
    kind: spec.kind,
    provenance: spec.provenance,
    metrics: spec.metrics || null,
    current,
    quantile,
    sample,
    mean,
    median,
    p10,
    p90,
    /** How wide the forecast is, as a fraction of the median. */
    spread: median > 0 ? (p90 - p10) / median : 0,
  };
}

/**
 * Project a whole trajectory forward, year by year, by re-applying the
 * one-step model to its own output. stopping.js uses this to build the
 * transition kernel its dynamic program runs on.
 */
function simulatePaths(features, years, nPaths, seed, opts) {
  const rng = makeRng(seed);
  const paths = [];

  for (let k = 0; k < nPaths; k++) {
    const row = [];
    let income = fNum(features.currentIncome);
    let age = fNum(features.age);

    for (let y = 0; y < years; y++) {
      const step = predict(Object.assign({}, features, { currentIncome: income, age }), opts);
      income = Math.max(0, step.quantile(rng()));
      age += 1;
      row.push(income);
    }
    paths.push(row);
  }
  return paths;
}

/* ---------------------------------------------------------------------------
 * Plain global, plus a CommonJS tail so the Node test suite can require it.
 * ------------------------------------------------------------------------ */
const Forecast = {
  predict,
  simulatePaths,
  loadModel,
  hasTrainedModel,
  probit,
  makeRng,
  repairCrossing,
  /** Exposed so test/verify_export.js can check the exact scorer the browser uses. */
  scoreQuantileForTest: scoreQuantile,
  walkTreeForTest: walkTree,
  priorParams,
  PRIOR_PARAMS,
};

if (typeof window !== 'undefined') window.Forecast = Forecast;
if (typeof module !== 'undefined' && module.exports) module.exports = Forecast;
